<a href="https://colab.research.google.com/github/gauravml/NUMPY/blob/main/NumpyLinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arithmetic on Numpy

## Prep

Let's recall how to access data in lists. For that we will leverage the dataset for this course, whch is the results of an actual behavioural experiment conducted by Universidad de la Matanza (UNLaM)

In [1]:
%%writefile get_data.sh
if [ ! -f dataset.csv ]; then
  wget -O dataset.csv https://www.dropbox.com/s/9t5lc04vxwvjvo6/dataset.csv?dl=0
fi

Writing get_data.sh


In [2]:
!bash get_data.sh


--2025-05-06 22:02:20--  https://www.dropbox.com/s/9t5lc04vxwvjvo6/dataset.csv?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.5.18, 2620:100:601d:18::a27d:512
Connecting to www.dropbox.com (www.dropbox.com)|162.125.5.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.dropbox.com/scl/fi/vdpumrhhu5yhwhgmzwday/dataset.csv?rlkey=ezm9dpl2wbkd1tzxqrn2rzrrn&dl=0 [following]
--2025-05-06 22:02:20--  https://www.dropbox.com/scl/fi/vdpumrhhu5yhwhgmzwday/dataset.csv?rlkey=ezm9dpl2wbkd1tzxqrn2rzrrn&dl=0
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc0e94a2d79b41d61d4b0fa234b0.dl.dropboxusercontent.com/cd/0/inline/CpP582I3Zi4jpsH1BAEuvAdSCuQPPhAOR5WwfJx-nAF5P4hFKYyHVpZtuH5v3yVVp-83XBU_QTDaWHiHuGYU3OA7flGG2gpdoAPdg1GM-Y-51Zfz53v__J5yJLwV2niHpNpe8R56MjcPLFQpZksCoFq1/file# [following]
--2025-05-06 22:02:20--  https://uc0e94a2d79b41d61d4b0fa234b0.dl.dropboxusercontent.com/c

In [3]:
import numpy as np

In [4]:
numpy_arr = np.genfromtxt('dataset.csv', delimiter=',')

## Basic Linear Algebra

Given two Numpy arrays, we can also do classical Matrix multiplication and addition.

In [5]:
a = numpy_arr[2:6, 7:11]
b = numpy_arr[23:27, 3:7]

In [6]:
print(f'a shape is {a.shape} and b shape is {b.shape}')

a shape is (4, 4) and b shape is (4, 4)


In [7]:
a + b

array([[4.  , 6.  , 6.  , 6.33],
       [5.  , 6.  , 6.34, 6.33],
       [4.  , 8.  , 6.66, 7.  ],
       [3.  , 6.  , 6.33, 6.67]])

In [8]:
a.dot(b)  # Remember a * b is elementwise

array([[ 4.    , 28.66  , 29.4289, 57.32  ],
       [ 5.    , 33.67  , 34.99  , 67.67  ],
       [ 5.    , 29.99  , 31.0989, 60.65  ],
       [ 4.    , 27.34  , 28.2211, 54.68  ]])

Let's verify it is indeed the matrix multiplication because it will fails if the dimensions rule doesn't comply

In [9]:
b = numpy_arr[23:26, 3:7]
b.shape

(3, 4)

In [10]:
a.dot(b)

ValueError: shapes (4,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [11]:
b.dot(a)

array([[28.    , 36.    , 34.    , 21.34  ],
       [23.68  , 29.35  , 27.9011, 17.01  ],
       [36.32  , 46.65  , 44.0989, 28.    ]])

Indeed it is matrix multiplication

## Solving a linear system

In numpy we can do the normal linear algebra operations. For example, we can solve the system:

```
A*x = b
```
Where the shapes are:
```
A -> (n,m)
x -> (m, 1)
b -> (m,1)
```

In [19]:
A = numpy_arr[5:10, 5:10].reshape(5,5)
b = numpy_arr[6, 5:10].reshape(5,1)

In [17]:
print(f'A shape is {A.shape} and b shape is {b.shape}')

A shape is (4, 5) and b shape is (5, 1)


In [21]:
x = np.linalg.inv(A).dot(b)

In [22]:
x

array([[   2.01515152],
       [-161.26020202],
       [-161.81691919],
       [-162.05363636],
       [ 484.9040404 ]])